### ISSUE TITLE
logging configuration, defaults & documentation

### ISSUE THREAD

**Issue by jillesvangurp** [dekellum/fishwife#6]
I want to use a custom logback.xml and have some java dependencies that log as well so I want to use the same config everywhere. Normally you configure logback by either passing in a -D property or by making sure logback.xml is on the classpath. Neither approach works with fishwife because it imposes a default configuration. This is true with both the slf4j and logback option. 

The way to fix this is to write your own start script and making sure to require 'rjack-slf4j/nop' instead of rjack-slf4j/simple. After that, if you have the logback jar on the classpath, it will initialize with the correct configuration. In my custom start script, I actually load a couple of jar files (including slf4j and logback) before fishwife starts. 

Probably just documenting this would help a lot (it took me a bit of time to figure this out). Also, it would be nice if the fishwife script did the right thing if valid log4j or logback configuration is on the classpath already or would have an option to take a logback configuration file as a parameter.

**Comment by dekellum** [comment]
Part of the confusion in this environment is over differing opinions on where to draw the line between java-way and ruby-way. I've generally sided on the ruby side for the configuration topic, but for logging in particular I've tried to keep it flexible enough to support all SLF4J output adaptors and config options.

### custom launcher

You mention writing your own start script. I encourage that and typically do the same.  This allows you total control of all details. I've packaged several complete sinatra apps as gems with fishwife and rjack-logback as dependencies.  One public example is: https://github.com/dekellum/boxed-geminabox

In particular: https://github.com/dekellum/boxed-geminabox/blob/master/init/boxed-geminabox
- Hashdot headers for daemonizing, log redirection, and integration with Iyyov process monitor (Might explain why I am less interested in Mizuno's later attempts at process control.)
- Logback custom configuration specific to the daemon/production mode.
- Using Hooker to externalize a minimal set of application and deployment-specific configuration (see also config/config.rb sample in same repo)

### fishwife launcher

In general `fishwife` or `rackup` make good quick demonstration launchers, or for config.ru compatibility with other servers. The intent with `fishwife` is to bring up a basic but functioning log output. If you want logback as the output adaptor, why not `gem install rjack-logback` or include via bundler?  Then, if you really want to use a logback.xml instead of ruby based config, you can do the following in your config.ru:

``` ruby
RJack::Logback.configure do
  RJack::Logback.load_xml_config( 'sample-logback.xml' )
end
```

### rackup launcher

See fishwife/example/config.ru for an example that works with rackup.  When using `rackup [-s Fishwife]`, no SLF4J output adaptor is loaded at all. You can arrange for any of these yourself.

Finally, see the logging section of the fishwife/README. Might consider this thread source material to be later integrated in the README which definitely has room for improvement.

**Comment by jillesvangurp** [comment]
Thanks for the very detailed response. This is very helpful.

**Comment by dekellum** [comment]
Referenced in README given the useful question and notes here.
