### ISSUE TITLE
:async in fishwife

### ISSUE THREAD

**Issue by efi** [dekellum/fishwife#7]
Hi there.

Do you see any chance of :async rack handling getting supported in fishwife?

Or the other way around: Why exactly has this functionality of mizuno been stripped from fishwife? (https://github.com/matadon/mizuno/blob/master/lib/mizuno/rack_handler.rb#L79)

Many thanks

Thomas

**Comment by dekellum** [comment]
I would say that while the async. support in MIzuno has always been a bit of a mystery and suspect to me, I am not aware of any removal of the feature in the Fishwife fork.  I did disable a spec associated with this in Fishwife since it was failing intermittently at that time. I'm happy to hear more details (bug report for this feature) or accept pull requests to fix the feature or implement reliable specs.
